#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
PROJECT_PATH="$SCRIPT_DIR/src"
GODOT_BIN="Godot"

[[ " $* " =~ " -h " ]] && HEADLESS=true || HEADLESS=false
[[ " $* " =~ " -f " ]] && FILTER=true || FILTER=false
[[ " $* " =~ " --help " ]] && HELP=true || HELP=false


CMD_ARGS=("--path" "$PROJECT_PATH")

if [[ "$HEADLESS" == true || "$HELP" == true ]]; then
    CMD_ARGS+=("--headless")
fi

USER_ARGS=()
for arg in "$@"; do
    [[ "$arg" != "-h" && "$arg" != "-f" ]] && USER_ARGS+=("$arg")
done

if [[ "$FILTER" == true || "$HELP" == true ]]; then
    $GODOT_BIN "${CMD_ARGS[@]}" -- "${USER_ARGS[@]}" | sed -n '/<game-output>/,/<\/game-output>/p' | sed '/<game-output>/d; /<\/game-output>/d'
else
    $GODOT_BIN "${CMD_ARGS[@]}" -- "${USER_ARGS[@]}"
fi
